version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: my-db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo

  myapp:
    build: .
    ports:
      - 8085:8080
    depends_on:
      - mongo

