name: Test CI

on:
  workflow_dispatch:

  push:



jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'


      - name: Build Jar
        run: mvn test