name: Test CI

on:
  push:
  pull_request:


jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopts'
          java-version: '11'


      - name: Build Jar
        run: mvn test